/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bai4;

import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Nguyen Quoc Chung
 */
public class Baii4 extends javax.swing.JFrame {

    /**
     * Creates new form Baii4
     */
    public Baii4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mylist = new javax.swing.JList<>();
        btnInput = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        checkbValid = new javax.swing.JCheckBox();
        btnTodenchan = new javax.swing.JButton();
        btnTodenle = new javax.swing.JButton();
        btnTodenSNT = new javax.swing.JButton();
        btnBotoden = new javax.swing.JButton();
        btnDeltoden = new javax.swing.JButton();
        btnSum = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("THAO TÁC TRÊN JLIST - CHECKBOX");

        jScrollPane1.setViewportView(mylist);

        btnInput.setText("Nhập");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        checkbValid.setText("Cho nhập số âm");

        btnTodenchan.setText("Tô đen số chẵn");
        btnTodenchan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenchanActionPerformed(evt);
            }
        });

        btnTodenle.setText("Tô đen số lẻ");
        btnTodenle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenleActionPerformed(evt);
            }
        });

        btnTodenSNT.setText("Tô đen số nguyên tố");
        btnTodenSNT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodenSNTActionPerformed(evt);
            }
        });

        btnBotoden.setText("Bỏ tô đen");
        btnBotoden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotodenActionPerformed(evt);
            }
        });

        btnDeltoden.setText("Xóa các giá trị đang tô đen");
        btnDeltoden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeltodenActionPerformed(evt);
            }
        });

        btnSum.setText("Tổng các giá trị trong JList");
        btnSum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumActionPerformed(evt);
            }
        });

        btnExit.setText("Đóng chương trình");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTodenchan)
                    .addComponent(btnTodenle)
                    .addComponent(btnTodenSNT)
                    .addComponent(btnBotoden)
                    .addComponent(btnDeltoden)
                    .addComponent(btnSum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnInput)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkbValid))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(btnExit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInput)
                    .addComponent(txtInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkbValid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnTodenchan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTodenle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTodenSNT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBotoden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeltoden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSum))
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(btnExit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        String value = txtInput.getText().trim();
        int i = Integer.parseInt(value);
        if (checkbValid.isSelected() == false) {
            if (value.equals("") || i < 0) {
                JOptionPane.showMessageDialog(this, "Please Enter Number > 0");
            } else {
                String item = txtInput.getText().trim();
                if (item.equals("")) {
                    JOptionPane.showMessageDialog(null,
                            "Pleas enter item add to Jlist", "Error",
                            JOptionPane.ERROR_MESSAGE);
                } else {
                    DefaultListModel model = (DefaultListModel) mylist.getModel();
                    model.addElement(item);
                    mylist.setModel(model);
                    txtInput.setText("");
                }
            }
        } else {
            if (value.equals("")) {
                JOptionPane.showMessageDialog(this, "Please Enter Number.");
            } else {

            }
        }

    }//GEN-LAST:event_btnInputActionPerformed

    private JList<String> createList() {
        // create defaultListModel
        DefaultListModel<String> model = new DefaultListModel<>();
        // add element to model
        model.addElement("Java");
        model.addElement("C#");
        // set model to JList
        mylist = new JList<String>(model);
        return mylist;
    }
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        JOptionPane.showConfirmDialog(this, "Ban muon dong chuong trinh?", "Warning", dialogButton);
        if (dialogButton == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnTodenchanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenchanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodenchanActionPerformed

    private void btnTodenleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodenleActionPerformed

    private void btnTodenSNTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodenSNTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTodenSNTActionPerformed

    private void btnBotodenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotodenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBotodenActionPerformed

    private void btnDeltodenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeltodenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeltodenActionPerformed

    private void btnSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baii4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baii4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baii4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baii4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baii4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBotoden;
    private javax.swing.JButton btnDeltoden;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnSum;
    private javax.swing.JButton btnTodenSNT;
    private javax.swing.JButton btnTodenchan;
    private javax.swing.JButton btnTodenle;
    private javax.swing.JCheckBox checkbValid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> mylist;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
